#!/bin/bash

if [[ $(pip3 show setuptools) ]];
then
				echo 'setuptools has already been installed'
else
				echo 'installing setuptools'
				pip3 install setuptools
fi

if [[ $(pip3 show wheel) ]];
then
				echo 'wheel has already been installed'
else
				echo 'installing wheel'
				pip3 install wheel
fi

if [[ $(pip3 show selenium) ]];
then
				echo 'selenium has already been installed'
else
				echo 'installing selenium'
fi

if [[ $(pip3 show bs4) ]];
then
				echo 'bs4 has already been installed'
else
				echo 'installing bs4'
				pip3 install bs4
fi

unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac
echo "Operating System: [${machine}]"

fridge='swiftweets.json'
if [ ! -e ${fridge} ];
then
				echo "Move fridge into the house"
				touch ${fridge}
fi
echo "Fridge has been powered on"

echo 'Start the server'
python3 swiftweet_feeder.py
